# Generated by Django 5.2 on 2025-04-24 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('رفيع', 'رفيع'), ('عريض', 'عريض')], default='رفيع', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'نوع طبلية',
                'verbose_name_plural': 'أنواع طبليات',
                'ordering': ['type', 'weight'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='pallet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.pallettype'),
        ),
    ]
