# Generated by Django 5.2 on 2025-04-24 17:36

from django.db import migrations


def create_default_pallet_types(apps, schema_editor):
    PalletType = apps.get_model('invoices', 'PalletType')
    
    # Create default pallet types
    pallet_types = [
        {'type': 'رفيع', 'weight': 9, 'name': 'رفيع 9'},
        {'type': 'رفيع', 'weight': 10, 'name': 'رفيع 10'},
        {'type': 'رفيع', 'weight': 18, 'name': 'رفيع 18'},
        {'type': 'عريض', 'weight': 10, 'name': 'عريض 10'},
        {'type': 'عريض', 'weight': 20, 'name': 'عريض 20'},
    ]
    
    for pallet_data in pallet_types:
        PalletType.objects.create(**pallet_data)

def update_existing_invoices(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    PalletType = apps.get_model('invoices', 'PalletType')
    
    # Get the default pallet type (رفيع 9)
    default_pallet = PalletType.objects.filter(type='رفيع', weight=9).first()
    if default_pallet:
        # Update all existing invoices that don't have a pallet type
        Invoice.objects.filter(pallet_type__isnull=True).update(pallet_type=default_pallet)

def reverse_default_pallet_types(apps, schema_editor):
    PalletType = apps.get_model('invoices', 'PalletType')
    PalletType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_pallettype_invoice_pallet_type'),
    ]

    operations = [
        migrations.RunPython(create_default_pallet_types, reverse_default_pallet_types),
        migrations.RunPython(update_existing_invoices, migrations.RunPython.noop),
    ]
