# Generated by Django 5.2 on 2025-04-23 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('number', models.PositiveIntegerField(default=1)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(null=True, unique=True)),
                ('supplier_name', models.CharField(default='', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SafeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('balance_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.balanceentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='صورة الشيك/التحويل')),
                ('supply_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.supplyorder')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('IN', 'Supply In'), ('OUT', 'Sale Out')], max_length=3)),
                ('tons', models.DecimalField(decimal_places=3, max_digits=10)),
                ('original_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoices.invoice')),
                ('supply_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.supplyorder')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('supply_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.supplyorder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
