# Generated by Django 5.2 on 2025-04-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_safetransaction_balance_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorder',
            name='tons',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
